Demo1/Areas/Admin/Controllers/LoginAdminController.cs
<<<<<<< HEAD
﻿using System;
=======
﻿using Demo1.Models;
using System;
>>>>>>> c4a09e5439a62284f0cf338ff661667fe350cd4d
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo1.Areas.Admin.Controllers
{
    public class LoginAdminController : Controller
    {
        // GET: Admin/LoginAdmin
<<<<<<< HEAD
=======
        MyDataDataContext db = new MyDataDataContext();
        [HttpGet]
>>>>>>> c4a09e5439a62284f0cf338ff661667fe350cd4d
        public ActionResult Login()
        {
            return View();
        }
<<<<<<< HEAD
=======
        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            //gán các giá trị người dùng nhập liệu cho các biến
            var tendn = collection["MSSV"];
            var matkhau = collection["PASS"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Error1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Error2"] = "Phải nhập mật khẩu";
            }
            else
            {
                // Gán giá trị cho đối tượng được tạo mới(admin)
                NGUOIDUNG admin = db.NGUOIDUNGs.SingleOrDefault(n => n.MSSV == tendn && n.PASS == matkhau);
                if (admin != null && admin.MAQUYEN == 1)
                {
                    Session["TaiKhoanAdmin"] = admin;
                    return RedirectToAction("Index", "HomeAdmin");
                }
                else
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return this.Login();
        }
        public ActionResult Logout()
        {
            Session["TaiKhoanAdmin"] = "";
            return RedirectToAction("Login", "HomeAdmin");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(FormCollection collection, NGUOIDUNG nd)
        {
            var check = db.NGUOIDUNGs.Where(m => m.MSSV == nd.MSSV).FirstOrDefault();
            if (check != null)
            {
                ViewData["CheckMail"] = "Tài Khoản Này Đã Được Sử Dụng";
                return this.Register();
            }
            else
            {
                var MSSV = collection["MSSV"];
                var TenSV = collection["HOVATEN"];
                var sdt = collection["SDT"];
                var GioiTinh = collection["GIOITINH"];
                var Gmail = collection["GMAIL"];
                var Lop = collection["LOP"];

                //Gán giá trị cho đổi tượng được tạo mới (kh)
                nd.MSSV = MSSV;
                nd.PASS = "123";
                nd.HOVATEN = TenSV;
                nd.SDT = sdt;
                nd.GIOITINH = int.Parse(GioiTinh);
                nd.GMAIL = Gmail;
                nd.LOP = Lop;
                nd.MAQUYEN = 1;

                db.NGUOIDUNGs.InsertOnSubmit(nd);
                db.SubmitChanges();
                
            }
            return RedirectToAction("Index", "TaiKhoanAdmin");
        }
>>>>>>> c4a09e5439a62284f0cf338ff661667fe350cd4d
    }
}

Demo1/Areas/Admin/Views/LoginAdmin/Login.cshtml
<<<<<<< HEAD
﻿@{
    ViewBag.Title = "ĐĂNG NHẬP TRANG QUẢN TRỊ";
    Layout = null;
}
=======
﻿@model Demo1.Models.NGUOIDUNG

@{
    ViewBag.Title = "Đăng nhập admin";
    Layout = null;
}



>>>>>>> c4a09e5439a62284f0cf338ff661667fe350cd4d
<link href="~/Areas/Admin/Content/css/StyleLogin.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<head>
    <title>Login Admin</title>
</head>
<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
        <!-- Icon -->
        <div class="fadeIn first">
            <img src="~/Areas/Admin/Content/img/logo_hutech.png" id="icon" alt="User Icon" />
            <h1>Login Admin</h1>
        </div>
        <h5 style="color:red; text-align:center"> @ViewBag.ThongBao</h5>

<<<<<<< HEAD
        @*@using (Html.BeginForm("Login", "LoginAdmin", FormMethod.Post, new { id = "formInput", @class = "form-control" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
            <div>
                <div>
                    <input type="text" id="login" class="fadeIn second" name="username" placeholder="Tên đăng nhập">
                    <br />
                    @*@ViewData["Error1"]*@
                </div>
                <div>
                    <input type="password" id="password" class="fadeIn third" name="password" placeholder="Mật khẩu">
                    <br />
                    @*@ViewData["Error2"]*@
                </div>
                <div>
                    <a href="@Url.Action("Index", "HomeAdmin")"><input type="submit" class="fadeIn fourth" value="Đăng nhập" /></a>
                    
                </div>
            </div>
        @*}*@
    </div>
</div>
@*@section scripts {
        <script>
            $(document).ready(function () {
                $("#formInput").validate({
                    rules: {
                        username: {
                            required: true
                        },
                        password: {
                            required: true,
                        }
                    },
                    messages: {
                        username: {
                            required: "Không được để trống"
                        },
                        password: {
                            required: "Không được để trống",
                        }
                    }
                })
            });
        </script>
    }*@
=======
        @using (Html.BeginForm("Login", "LoginAdmin", FormMethod.Post, new { id = "formInput", @class = "form-control" }))
        {
            @Html.AntiForgeryToken()
            <div>
                <div>
                    <div class="col-md-10">
                        <input placeholder="Tên đăng nhập"
                               @Html.EditorFor(model => model.MSSV, new { htmlAttributes = new { @id = "login", @class = "fadeIn second" } })
                               @Html.ValidationMessageFor(model => model.MSSV, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div>
                    <div class="col-md-10">
                        <input type="password" placeholder="Mật khẩu"
                               @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @id = "password", @class = "fadeIn third" } })
                               @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div>
                    <a href="#"><input type="submit" class="fadeIn fourth" value="Đăng nhập" /></a>
                </div>
            </div>
        }
    </div>
</div>

>>>>>>> c4a09e5439a62284f0cf338ff661667fe350cd4d

Demo1/Areas/Admin/Views/LoginAdmin/Register.cshtml
@model Demo1.Models.NGUOIDUNG

@{
    ViewBag.Title = "Register";
}

<h2 style="text-align:center">TẠO TÀI KHOẢN QUẢN TRỊ VIÊN MỚI</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            <input placeholder="Họ và tên" id="HOVATEN" type="text" name="HOVATEN"
                   @Html.EditorFor(model => model.HOVATEN, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.HOVATEN, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input placeholder="MSSV hoặc tên đăng nhập" id="MSSV" type="text" name="MSSV"
                   @Html.EditorFor(model => model.MSSV, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.MSSV, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <div class="col-md-10">
                <input name="GIOITINH" type="radio" value="1" />Nam
                <input name="GIOITINH" type="radio" value="0" />Nữ
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input placeholder="Số điện thoại" id="SDT" type="text" name="SDT"
                   @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input placeholder="Gmail" id="GMAIL" type="text" name="GMAIL"
                   @Html.EditorFor(model => model.GMAIL, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.GMAIL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input placeholder="Lớp " id="LOP" type="text" name="LOP"
                   @Html.EditorFor(model => model.LOP, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.LOP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Tạo thành viên" class="btn btn-primary" />
            <a href="@Url.Action("Index", "TaiKhoanAdmin")" class="btn btn-danger">
                Quay lại
            </a>
        </div>
    </div>
</div>
}